---
- name: Download Docker (linux container)
  get_url:
    url: "https://get.docker.com/ubuntu/"
    validate_certs: no
    dest: "/home/{{ username }}/setup/docker.sh"
  sudo: yes

- name: install Panamax running script
  shell: "/home/{{ username }}/setup/docker.sh"
  sudo: yes

