---
- name: Download composer
  get_url:
    url: "https://getcomposer.org/installer"
    dest: "/home/{{ username }}/ubuntu-provision/composer"
    validate_certs: no
  sudo: yes

- name: Install Composer
  command: "php /home/{{ username }}/ubuntu-provision/composer"
  sudo: yes

- name: Move composer to /usr/local/bin/composer
  shell: "mv composer.phar /usr/local/bin/composer"
  sudo: yes

- name: Create composer symlink
  file:
    src: /usr/local/bin/composer
    dest: /usr/bin/composer
    state: link
  sudo: yes

- name: Compile Drush with Composer
  command: "composer global require drush/drush:dev-master"
  sudo: yes

- name: Change ~/.drush folder permissions
  file:
    path: "/home/{{ username }}/.drush"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
    state: directory
  sudo: yes
  
- name: Install usefull drush modules
  command: "drush dl registry_rebuild site_audit drupalgeddon drush-vagrant drupal-up aegir-up drush-hosts"
  args:
    chdir: "~/.drush"
  
- name: Install Drush-patchfile
  git:
    repo: "https://bitbucket.org/davereid/drush-patchfile"
    dest: "/home/{{ username }}/.drush/drush-patchfile"
    version: master
    force: yes
    accept_hostkey: yes
  tags: drush
  
