---
- name: Download composer
  get_url:
    url: "https://getcomposer.org/installer"
    dest: "/home/{{ username }}/setup/composer"
    validate_certs: no
  sudo: yes

- name: Install Composer
  command: "php /home/{{ username }}/setup/composer"
  sudo: yes

- name: Move composer to /usr/local/bin/composer
  shell: "mv composer.phar /usr/local/bin/composer"
  sudo: yes

- name: Create composer symlink
  file:
    src: /usr/local/bin/composer
    dest: /usr/bin/composer
    state: link
  sudo: yes

- name: Clone drush from github
  git:
    repo: "git://github.com/drush-ops/drush.git"
    dest: /usr/local/src/drush
    version: "{{ drush_version }}"
    force: yes
    accept_hostkey: yes
  tags: drush

- name: Create Drush symlink
  file:
    src: /usr/local/src/drush/drush
    dest: /usr/bin/drush
    state: link
  sudo: yes

- name: Compile Drush with Composer
  command: "composer install"
  args:
    chdir: "/usr/local/src/drush"

- name: Check drush has been installed
  command: "drush --version"

