---
- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php
  sudo: yes

- name: Move composer to /usr/local/bin/composer
  shell: mv composer.phar /usr/local/bin/composer
  sudo: yes

- name: Create composer symlink
  file:
    src: /usr/local/bin/composer
    dest: /usr/bin/composer
    state: link
  sudo: yes

- name: Clone drush from github
  git:
    repo: git://github.com/drush-ops/drush.git
    dest: /usr/local/src/drush
    force: yes
    accept_hostkey: yes
    version={{ drush_version }}
  when: result.rc !=0
  tags: drush

- name: Create Drush symlink
  file:
    src: /usr/local/src/drush/drush
    dest: /usr/bin/drush
    state: link
  sudo: yes

- name: Compile Drush with Composer
  shell: composer install
  args:
    chdir: /usr/local/src/drush/drush

- name: Check drush has been installed
  command: drush --version

