---
- name: download fixubuntu
  get_url:
    url: https://fixubuntu.com/fixubuntu.sh
    dest: "/home/{{ username }}/setup/fixubuntu.sh"
    mode: 0755

- name: run fixubuntu
  command: "/home/{{ username }}/setup/fixubuntu.sh"
  sudo: yes
