---
- name: Create git-ftp folder
  file:
    path: "/opt/git-ftp"
    state: directory
  sudo: yes

- name: Clone git-ftp from Github
  git:
    repo: "git://github.com/git-ftp/git-ftp.git"
    dest: "/opt/git-ftp/"
    force: yes
    accept_hostkey: yes
  sudo: yes

- name: Compile with make install
  command: make install
  args:
    chdir: "/opt/git-ftp"
  sudo: yes

