---
- name: Install g++
  apt:
    name: g++
  sudo: yes
  
- name: Create /opt/node folder
  file:
    path: "/opt/node"
    state: directory
  sudo: yes
    
- name: Checkout nodejs from GitHub
  git:
    repo: "git://github.com/joyent/node.git"
    dest: "/opt/node"
    force: no
    accept_hostkey: yes
    version: "{{ node_version }}"
  tags: nodejs
  sudo: yes

- name: configure
  sudo: yes
  command: "./configure"
  args:
    chdir: "/opt/node"
  tags: nodejs

- name: make
  command: make
  sudo: yes
  args:
    chdir: "/opt/node"
  tags: nodejs

- name: make install
  command: "make install"
  args:
    chdir: "/opt/node"
  tags: nodejs
  sudo: yes

- name: install global nodejs packages
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items:
    - bower
    - grunt-cli
    - yo
    - browser-sync
    #- cordova
    #- ionic
  sudo: yes
