---
- name: Install fish shell
  apt:
    name: fish
    update_cache: yes
  sudo: yes

- name: Download oh-my-fish
  git:
    repo: "git://github.com/bpinto/oh-my-fish.git"
    dest: "/home/{{ username }}/.oh-my-fish"

- name: Set fish as the default shell 1
  shell: "chsh -s \\$(which fish)"
  sudo: yes

- name: Set fish as the default shell 2
  shell: "/bin/grep ^\\$(which fish) /etc/shells -q"
  sudo: yes

- name: fish - make sure personal fish-tplcom.load file exists
  file:
    path: "/home/{{ username }}/dotfiles/oh-my-fish/fish-tplcom.load"
    state: file

- name: fish - create a symlink to my personal fish-tplcom.load file
  file:
    src: "/home/{{ username }}/dotfiles/oh-my-fish/fish-tplcom.load"
    dest: "/home/{{ username }}/.oh-my-fish/custom/fish-tplcom.load"
    state: link

- name: fish - make sure local fish configuration file exists
  file:
    path: "/home/{{ username }}/dotfiles/oh-my-fish/config.fish"
    state: file

- name: fish - create a symlink to my local fish configuration
  file:
    src: "/home/{{ username }}/dotfiles/oh-my-fish/config.fish"
    dest: "/home/{{ username }}/.config/fish/config.fish"
    state: link


