---
- name: Install oh-my-fish
  get_url: 
    url: "https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish"
    dest: "/home/{{ username }}/setup/install.fish"
  sudo: yes

- name: Run fish installer
  shell: "bin/sh /home/{{ username }}/setup/install.fish"
  sudo: yes 
  
- name: Set fish as the default shell 1
  command: "grep -q ^/usr/local/bin/fish$ /etc/shells"
  sudo: yes

- name: Set fish as the default shell 2
  command: "chsh -s /usr/local/bin/fish"
  sudo: yes

- name: fish - make sure personal fish-tplcom.load file exists
  file:
    path: "/home/{{ username }}/dotfiles/oh-my-fish/fish-tplcom.load"
    state: file

- name: fish - create a symlink to my personal fish-tplcom.load file
  file:
    src: "/home/{{ username }}/dotfiles/oh-my-fish/fish-tplcom.load"
    dest: "/home/{{ username }}/.oh-my-fish/custom/fish-tplcom.load"
    state: link

- name: fish - make sure local fish configuration file exists
  file:
    path: "/home/{{ username }}/dotfiles/oh-my-fish/config.fish"
    state: file

- name: fish - create a symlink to my local fish configuration
  file:
    src: "/home/{{ username }}/dotfiles/oh-my-fish/config.fish"
    dest: "/home/{{ username }}/.config/fish/config.fish"
    state: link


