---
- name: Install fish shell
  apt:
    name: fish
    update_cache: yes
  sudo: yes

- name: Download oh-my-fish
  git:
    repo: "git://github.com/bpinto/oh-my-fish.git"
    dest: "/home/{{ username }}/.oh-my-fish"

- name: Set fish as the default shell 1
  user:
    name: "{{ username }}"
    shell: /usr/bin/fish
  sudo: yes

- name: fish - make sure personal fish-tplcom.load file exists
  file:
    path: "/home/{{ username }}/dotfiles/oh-my-fish/fish-tplcom.load"
    state: file

- name: fish - create a symlink to my personal fish-tplcom.load file
  file:
    src: "/home/{{ username }}/dotfiles/oh-my-fish/fish-tplcom.load"
    path: "/home/{{ username }}/.oh-my-fish/custom/fish-tplcom.load"
    state: link

- name: fish - create ~/.config/fish folder
  file:
    path: "/home/{{ username }}/.config/fish"
    state: directory
    force: yes

- name: fish - create a symlink to my local fish configuration
  file:
    src: "/home/{{ username }}/dotfiles/oh-my-fish/config.fish"
    path: "/home/{{ username }}/.config/fish/config.fish"
    state: link

- name: Clone z-fish from github
  git:
    repo: "git://github.com/sjl/z-fish.git"
    dest: "/home/{{ username }}/z-fish"
    force: no
    accept_hostkey: yes
  tags: z-fish
