---
- name: Download Panamax (docker GUI)
  get_url: 
    url: "http://download.panamax.io/installer/ubuntu.sh"
    dest: "/home/{{ username }}/setup/panamax.sh"
  sudo: yes

- name: install Panamax running script
  command: "sh panamax.sh"
  args:
    chdir: "/home/{{ username }}/setup/"
  sudo: yes
