---
- name: Install PHP5 and Apache2
  apt:
    pkg: "{{ item }}"
    with_items:
      - php5
      - libapache2-mod-php5
      - php5-mcrypt
    update_cache: yes
    force: yes
    state: installed
  sudo: yes
