---
- name: Purge openjdk*
  command: apt-get purge openjdk*
<<<<<<< HEAD
    force: yes
=======
>>>>>>> 46ae5f6f8eed2b36a56bf4153da2001759c0d594
  sudo: yes

- name: Add java in system repositories
  apt_repository:
    repo=ppa:webupd8team/java
    state=present
  sudo: yes

- name: Install java
  apt:
    name: oracle-java7-installer
    force: yes
  sudo: yes

- name: download phpstorm
  get_url:
    url: http://download.jetbrains.com/webide/PhpStorm-EAP-139.1226.tar.gz
    dest: /home/{{ username }}/setup/phpstorm.tar.gz
    mode: 0440

- name: extract phpstorm
  unarchive:
    src: /home/{{ username }}/setup/phpstorm.tar.gz
    dest: /home/{{ username }}/setup/phpstorm

- name: install phpstorm
<<<<<<< HEAD
  command: cd /home/{{ username }}/setup/phpstorm/bin
  command: ./phpstorm.sh
=======
  command: "./phpstorm.sh"
    chdir: "/home/{{ username }}/setup/phpstorm/bin"
>>>>>>> 46ae5f6f8eed2b36a56bf4153da2001759c0d594
  sudo: yes
