---
- name: Purge openjdk*
  command: apt-get purge openjdk*
  sudo: yes

- name: Add java in system repositories
  apt_repository:
    repo="ppa:webupd8team/java"
    state=present
  sudo: yes

- name: Install java
  apt:
    name: oracle-java7-installer
    force: yes
  sudo: yes

- name: download phpstorm
  get_url:
    url: "http://download.jetbrains.com/webide/PhpStorm-EAP-139.1226.tar.gz"
    dest: "/home/{{ username }}/setup/phpstorm.tar.gz"
    mode: 0440

- name: extract phpstorm
  unarchive:
    src: "/home/{{ username }}/setup/phpstorm.tar.gz"
    dest: "/home/{{ username }}/setup/phpstorm"

- name: install phpstorm
  command: "cd /home/{{ username }}/setup/phpstorm/bin"
  sudo: yes

- name: Compile phpstorm  
  command: "./phpstorm.sh"
  args:
    chdir: "/home/{{ username }}/setup/phpstorm/bin"
  sudo: yes
