---
- name: download phpstorm
  get_url:
    url: "{{ phpstorm_url }}"
    dest: "/home/{{ username }}/setup/phpstorm.tar.gz"
    mode: 0440

- name: extract phpstorm
  unarchive:
    src: "/home/{{ username }}/setup/phpstorm.tar.gz"
    dest: "/home/{{ username }}/setup/phpstorm"

- name: install phpstorm
  command: "cd /home/{{ username }}/setup/phpstorm/bin"
  sudo: yes

- name: Compile phpstorm  
  command: "./phpstorm.sh"
  args:
    chdir: "/home/{{ username }}/setup/phpstorm/bin"
  sudo: yes
