---
- name: install plank - add plank ppa
  apt_repository:
    repo: ppa:docky-core/stable
    state: present
    update_cache: yes
  sudo: yes

- name: install plank
  apt:
    name: plank
  sudo: yes

- name: install plank - Make sure that the autostart directory exsists
  file:
    path: /home/{{ username }}/.config/autostart
    state: directory

- name: install plank - Make Plank autostart
  file:
    src: /usr/share/applications/plank.desktop
    dest: /etc/xdg/autostart/
    state: link
  sudo: yes

- name: gnome-terminal launcher-hide-mode
  dconf:
    key: /org/compiz/profiles/unity/plugins/unityshell/launcher-hide-mode
    int: 1
