---
- name: Make sure that the setup directory exsists
  file:
    path: "/home/{{ username }}/ubuntu-provision"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
