---
- name: install Ruby
  apt:
    name: ruby
    update_cache: yes
  sudo: yes
  
- name: install scm-breeze - checkout repo
  git:
    repo: "git://github.com/ndbroadbent/scm_breeze.git"
    dest: "/home/{{ username }}/setup/scm_breeze"

- name: install scm-breeze - run script
  shell: "/home/{{ username }}/setup/scm_breeze/install.sh"
  sudo: yes

- name: Create /opt/rubygems folder
  file:
    path: "/opt/rubygems"
    state: directory
  sudo: yes

- name: Clone Rubygems
  git:
    repo: "git://github.com/rubygems/rubygems"
    dest: "/opt/rubygems"
    version: "{{ rubygems_vesrion }}"
  sudo: yes

- name: Compile Rubygems
  command: "ruby setup.rb"
  args:
    chdir: "/opt/rubygems"
  sudo: yes

- name: Install sass gem
  shell: "/usr/local/rvm/bin/rvm all do gem install {{ item }}"
  with_items:
    - capistrano
    - sass
    - boostrap-sass
    - compass
  sudo: yes

