---
- name: install Ruby
  apt:
    name: {{ item }}
    with_items:
      - build-essential
      - comerr-dev
      - dpkg-dev
      - fakeroot
      - git-core
      - krb5-multidev
      - libalgorithm-diff-perl
      - libalgorithm-diff-xs-perl
      - libalgorithm-merge-perl
      - libcurl4-openssl-dev
      - libfakeroot
      - libgcrypt11-dev
      - libgnutls-dev
      - libgnutlsxx27
      - libgpg-error-dev
      - libgssrpc4
      - libidn11-dev
      - libkadm5clnt-mit9
      - libkadm5srv-mit9
      - libkdb5-7
      - libkrb5-dev
      - libldap2-dev
      - libp11-kit-dev
      - libreadline-dev
      - librtmp-dev
      - libtasn1-6-dev
      - python-software-properties
      - ruby
    update_cache: yes
  sudo: yes
  
- name: install scm-breeze - checkout repo
  git:
    repo: "git://github.com/ndbroadbent/scm_breeze.git"
    dest: "/home/{{ username }}/setup/scm_breeze"

- name: install scm-breeze - run script
  shell: "/home/{{ username }}/setup/scm_breeze/install.sh"
  sudo: yes

- name: Install sass gem
  shell: "gem install {{ item }}"
  with_items:
    - capistrano
    - sass
    - boostrap-sass
    - compass
  sudo: yes

