---
- name: install Ruby from ppa
  apt_repository:
    repo: "ppa:brightbox/ruby-ng-experimental"
    state: present
    update_cache: yes
  sudo: yes

- name: install Ruby
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby2.1
    - ruby2.1-dev
    - ruby-switch
  sudo: yes

- name: Install some gems
  shell: "gem install {{ item }}"
  with_items:
  #  - capistrano
  #  - sass
  #  - boostrap-sass
  #  - compass
    - tmuxinator
  #  - autoprefixer-rails
    - bundler
  sudo: yes

