---
- name: install Ruby from ppa
  apt_repository:
    repo: "ppa:brightbox/ruby-ng-experimental"
    state: present
    update_cache: yes
  sudo: yes

- name: install Ruby
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby2.2
    - ruby2.2-dev
  sudo: yes

- name: Install sass gem
  shell: "gem install {{ item }}"
  with_items:
    - capistrano
    - sass
    - boostrap-sass
    - compass
    - tmuxinator
    - autoprefixer-rails
    - bundler
  sudo: yes

