---
- name: install Skype dependencies
  apt:
    name: "sni-qt:i386"
    update_cache: yes
  sudo: yes

- name: install gdebi
  apt:
    name: gdebi
    update_cache: yes
  sudo: yes

- name: enable MultiArch if installing on Ubuntu 64x
  shell: "dpkg --add-architecture i386"
  sudo: yes

- name: Download Skype
  get_url:
    url: "http://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb"
    dest: "/home/{{ username }}/setup"
  sudo: yes

- name: install Skype
  command: "gdebi skype-ubuntu-precise_4.3.0.37-1_i386.deb"
    chdir: "/home/{{ username }}/setup"
  sudo: yes
