---
- name: Install vim editor
  apt:
    name: vim
  sudo: yes

- name: Download spf13-vim script
  get_url:
    url: "http://j.mp/spf13-vim3"
    dest: "/home/{{ username }}/setup/spf13-vim.sh"

- name: Change ownership of spf13-vim script
  file:
    dest: "/home/{{ username }}/setup/spf13-vim.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Install spf13-vim
  when: /home/{{ username }}/setup/spf13-vim.sh.stat.exists == False
  shell: "/home/{{ username }}/setup/spf13-vim.sh"
  sudo: yes

- name: Remove ~/.vimrc.local
  command: "rm -f /home/{{ username }}/.vimrc.local"
  sudo: yes

- name: Create symlink ~/.vimrc.local
  file:
    src: "/home/{{ username }}/dotfiles/vim/vimrc.local"
    dest: "/home/{{ username }}/.vimrc.local"
    mode: 0755
    state: link

- name: Create symlink .vimrc.bundles.local
  file:
    src: "/home/{{ username }}/dotfiles/vim/vimrc.bundles.local"
    dest: "/home/{{ username }}/.vimrc.bundles.local"
    mode: 0755
    state: link

- name: vim - run bundle install
  when: "/home/{{ username }}/setup/spf13-vim.sh".stat.exists == False
  command: "vim +PluginInstall +BundleClean +qall"

