---
- name: Install several utilities and monitoring software
  apt: pkg={{ item }} state=latest
  with_items:
    - deja-dup
    - nautilus-open-terminal
#    - gparted
#    - keepass2
#    - vlc
    - filezilla
    - p7zip-full
#    - terminator
    - tmux
#    - smartmontools
    - gksu
    - leafpad
#    - lxc
  sudo: yes

- name: Symlink my own .{{ dotfile }} from dotfiles
  file:
    src: "/home/{{ username }}/dotfiles/{{ dotfile }}"
    path: "/home/{{ username }}/.{{ dotfile }}"
    with_items:
     - filezilla
     - config
     - gconf
     - profile
     - tmuxinator
    state: link

  
