---
- name: download vagrant .deb package
  get_url:
    url: "{{ vagrant_url }}"
    dest: "/home/{{ username }}/setup/vagrant.deb"
    validate_certs: no
    mode: 0755

- name: install vagrant
  apt:
    deb: "/home/{{ username }}/setup/vagrant.deb"
  sudo: yes
  
- name: install vagrant plugins
  command: "vagrant plugin install {{ item }}"
  with_items:
   - vagrant-cachier
   - vagrant-gatling-rsync
   - vagrant-share
   - vagrant-triggers
   - vagrant-vbguest

