---
- name: Install dkms package
  apt:
    name: dkms
  sudo: yes
  
- name: Download virtualbox .deb package
  get_url:
    url: "{{ virtualbox_url }}"
    dest: "/home/{{ username }}/ubuntu-provision/virtualbox.deb"
    mode: 0755

- name: Install virtualbox
  apt:
    deb: "/home/{{ username }}/ubuntu-provision/virtualbox.deb"
  sudo: yes
