---
username: tplcom
github_username: TheodorosPloumis

# Drush version, 
drush_version: master

# PHPstorm, https://www.jetbrains.com/phpstorm/download
phpstorm_url: http://download.jetbrains.com/webide/PhpStorm-EAP-139.1226.tar.gz

# Vagrant package, https://www.vagrantup.com/downloads.html
vagrant_url: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb

# VirtualBox, https://www.virtualbox.org/wiki/Linux_Downloads
virtualbox_url: http://download.virtualbox.org/virtualbox/4.3.20/virtualbox-4.3_4.3.20-96996~Ubuntu~raring_amd64.deb

